logging:
  level:
    ia.antop.gunpla: DEBUG
    org.springframework.security: INFO

server:
  servlet:
    context-path: /
app:
  box-art:
    original-directory: ./data/boxart/original
    thumbnail-directory: ./data/boxart/thumbnail
